/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CctvRouteImport } from './routes/cctv'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ManagedServicesRouteImport } from './routes/managed-services'
import { Route as NetworkingRouteImport } from './routes/networking'
import { Route as ServersRouteImport } from './routes/servers'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SlaRouteImport } from './routes/sla'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CctvRoute = CctvRouteImport.update({
  id: '/cctv',
  path: '/cctv',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagedServicesRoute = ManagedServicesRouteImport.update({
  id: '/managed-services',
  path: '/managed-services',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkingRoute = NetworkingRouteImport.update({
  id: '/networking',
  path: '/networking',
  getParentRoute: () => rootRouteImport,
} as any)
const ServersRoute = ServersRouteImport.update({
  id: '/servers',
  path: '/servers',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SlaRoute = SlaRouteImport.update({
  id: '/sla',
  path: '/sla',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cctv': typeof CctvRoute
  '/clients': typeof ClientsRoute
  '/contact': typeof ContactRoute
  '/managed-services': typeof ManagedServicesRoute
  '/networking': typeof NetworkingRoute
  '/servers': typeof ServersRoute
  '/services': typeof ServicesRoute
  '/sla': typeof SlaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cctv': typeof CctvRoute
  '/clients': typeof ClientsRoute
  '/contact': typeof ContactRoute
  '/managed-services': typeof ManagedServicesRoute
  '/networking': typeof NetworkingRoute
  '/servers': typeof ServersRoute
  '/services': typeof ServicesRoute
  '/sla': typeof SlaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cctv': typeof CctvRoute
  '/clients': typeof ClientsRoute
  '/contact': typeof ContactRoute
  '/managed-services': typeof ManagedServicesRoute
  '/networking': typeof NetworkingRoute
  '/servers': typeof ServersRoute
  '/services': typeof ServicesRoute
  '/sla': typeof SlaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cctv'
    | '/clients'
    | '/contact'
    | '/managed-services'
    | '/networking'
    | '/servers'
    | '/services'
    | '/sla'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cctv'
    | '/clients'
    | '/contact'
    | '/managed-services'
    | '/networking'
    | '/servers'
    | '/services'
    | '/sla'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/cctv'
    | '/clients'
    | '/contact'
    | '/managed-services'
    | '/networking'
    | '/servers'
    | '/services'
    | '/sla'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CctvRoute: typeof CctvRoute
  ClientsRoute: typeof ClientsRoute
  ContactRoute: typeof ContactRoute
  ManagedServicesRoute: typeof ManagedServicesRoute
  NetworkingRoute: typeof NetworkingRoute
  ServersRoute: typeof ServersRoute
  ServicesRoute: typeof ServicesRoute
  SlaRoute: typeof SlaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cctv': {
      id: '/cctv'
      path: '/cctv'
      fullPath: '/cctv'
      preLoaderRoute: typeof CctvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/managed-services': {
      id: '/managed-services'
      path: '/managed-services'
      fullPath: '/managed-services'
      preLoaderRoute: typeof ManagedServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/networking': {
      id: '/networking'
      path: '/networking'
      fullPath: '/networking'
      preLoaderRoute: typeof NetworkingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servers': {
      id: '/servers'
      path: '/servers'
      fullPath: '/servers'
      preLoaderRoute: typeof ServersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sla': {
      id: '/sla'
      path: '/sla'
      fullPath: '/sla'
      preLoaderRoute: typeof SlaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CctvRoute: CctvRoute,
  ClientsRoute: ClientsRoute,
  ContactRoute: ContactRoute,
  ManagedServicesRoute: ManagedServicesRoute,
  NetworkingRoute: NetworkingRoute,
  ServersRoute: ServersRoute,
  ServicesRoute: ServicesRoute,
  SlaRoute: SlaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
